import Layout from "@/components/Layout";
import Head from "next/head";
import profilePic from "../../public/images/profile/main.png";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow, EmailIcon, WhatsAppIcon, CopyIcon, CheckIcon } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import { useState } from "react";
import { createPortal } from "react-dom";
import { motion, AnimatePresence } from "framer-motion";
export default function Home() {
  const [showContact, setShowContact] = useState(false);
  const [copied, setCopied] = useState("");

  const handleCopy = (text) => {
    navigator.clipboard.writeText(text);
    setCopied(text);
    setTimeout(() => setCopied(""), 2000);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center w-full min-h-screen text-dark dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Profile Picture"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,(max-width: 1200px) 50vw,50vw"
              />
            </div>
            <div className="flex flex-col items-center self-center w-1/2 lg:w-full lg:text-center">
              <AnimatedText
                text={"Turning Vision Into Reality With Code And Design."}
                className="!text-6xl text-left xl:!text-5xl lg:!text-center lg:!text-5xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/dummy.pdf"
                  target="_blank"
                  className=" md:p-2 md:px-4 md:text-base hover:dark:border-light hover:dark:bg-dark hover:dark:text-light dark:bg-light dark:text-dark flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <button
                  onClick={() => setShowContact(true)}
                  className="ml-4 text-lg font-medium underline capitalize text-dark dark:text-light md:text-base"
                >
                  Contact
                </button>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute inline-block w-24 right-8 bottom-8 md:hidden">
          <Image src={lightBulb} alt="DR Developer" className="w-full h-auto" />
        </div>
      </main>

      {typeof document !== "undefined" &&
        createPortal(
          <AnimatePresence>
            {showContact && (
              <motion.div
                className="fixed inset-0 z-50 flex items-center justify-center bg-dark/60 backdrop-blur-sm"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setShowContact(false)}
              >
                <motion.div
                  className="relative w-full max-w-md p-8 mx-4 border border-solid rounded-2xl bg-light dark:bg-dark border-dark dark:border-light"
                  initial={{ scale: 0.8, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0.8, opacity: 0 }}
                  transition={{ type: "spring", duration: 0.5 }}
                  onClick={(e) => e.stopPropagation()}
                >
                  <button
                    onClick={() => setShowContact(false)}
                    className="absolute text-2xl top-4 right-4 text-dark dark:text-light hover:text-primary dark:hover:text-primaryDark"
                  >
                    &times;
                  </button>
                  <h2 className="mb-6 text-2xl font-bold text-dark dark:text-light">
                    Contact Me
                  </h2>
                  <div className="flex flex-col gap-4">
                    <div className="flex items-center gap-3 p-3 border border-solid rounded-lg border-dark/10 dark:border-light/10">
                      <a
                        href="mailto:dasanayakabandara81@gmail.com"
                        className="flex items-center flex-1 gap-3 min-w-0"
                      >
                        <span className="flex-shrink-0 w-8 text-primary dark:text-primaryDark">
                          <EmailIcon />
                        </span>
                        <span className="font-medium truncate text-dark dark:text-light">
                          dasanayakabandara81@gmail.com
                        </span>
                      </a>
                      <button
                        onClick={() => handleCopy("dasanayakabandara81@gmail.com")}
                        className="flex-shrink-0 p-2 transition-colors rounded-md text-dark/50 dark:text-light/50 hover:text-dark dark:hover:text-light hover:bg-dark/10 dark:hover:bg-light/20"
                      >
                        <span className="w-5">
                          {copied === "dasanayakabandara81@gmail.com" ? <CheckIcon className="text-green-500" /> : <CopyIcon />}
                        </span>
                      </button>
                    </div>
                    <div className="flex items-center gap-3 p-3 border border-solid rounded-lg border-dark/10 dark:border-light/10">
                      <a
                        href="https://wa.me/94754879676"
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-center flex-1 gap-3 min-w-0"
                      >
                        <span className="flex-shrink-0 w-8 text-[#25D366]">
                          <WhatsAppIcon />
                        </span>
                        <span className="font-medium truncate text-dark dark:text-light">
                          0754879676
                        </span>
                      </a>
                      <button
                        onClick={() => handleCopy("0754879676")}
                        className="flex-shrink-0 p-2 transition-colors rounded-md text-dark/50 dark:text-light/50 hover:text-dark dark:hover:text-light hover:bg-dark/10 dark:hover:bg-light/20"
                      >
                        <span className="w-5">
                          {copied === "0754879676" ? <CheckIcon className="text-green-500" /> : <CopyIcon />}
                        </span>
                      </button>
                    </div>
                  </div>
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>,
          document.body
        )}
    </>
  );
}
